name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Blog
      run: | 
        cd ../..
        hugo # 生成public文件夹
        cd public
        echo "punchcode.top" > CNAME
        git init
        git remote set-url origin git@github.com:huanruiz/huanruiz.github.io.git
        git remote add origin git@github.com:huanruiz/huanruiz.github.io.git
        git add .
        git commit -m 'init'
        git push -f --set-upstream origin master
        cd ..
        rm -rf public
      shell: bash

